server:
  port: 8088


logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR





#spring:
#  datasource:
#    url: jdbc:h2:file:./h2/code-generator;
#     plateform: h2
#        username: sa
#          password:

spring:
  h2:
    console:
      enabled: true






